### PR TITLE
Fix MarkdownStyleSheet.blockquote

### LINKED ISSUE #48: iframe content is not shown
i have something like this: 
`<iframe allow="autoplay; encrypted-media" allowfullscreen="" scrolling="no" src="https://www.youtube.com/embed/xxxxxxx" width="560" height="400" frameborder="0"></iframe></p>`
which is not shown and I don't know why :/ Any help?

### LINKED ISSUE #53: Dart 2 incompatibilities
Dart SDK constraint needs to be raised to accept 2.0 stable:
https://github.com/flutter/flutter_markdown/blob/master/pubspec.yaml#L21

Analysis is not passing:
```
15.12s$ flutter test
Running "flutter packages get" in flutter_markdown...        5.2s
00:07 +0: loading /home/travis/build/flutter/flutter_markdown/test/flutter_markdown_test.dart                                                                                                          compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:32:22: Error: The class 'TypeMatcher' is abstract and can't be instantiated.
compiler message:       : call = const TypeMatcher<Invocation>();
compiler message:                      ^^^^^^^^^^^
compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:1: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
compiler message: Try using a constructor or factory that is 'const'.
compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:32:22: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       : call = const TypeMatcher<Invocation>();
```

### LINKED ISSUE #58: & to &amp; is BUG?
https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&h=350

to

https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=350

### LINKED ISSUE #62: Allow MarkdownBody to shrink horizontally
I use `MarkdownBody` like this:

```dart
MarkdownBody(
  data: "foobar"
)
```

and it fills the whole width of the parent widget. I want it to shrink to only use width required to render `foobar` text. 

I found, that changing [this line](https://github.com/flutter/flutter_markdown/blob/265676fcaed7fab9b68e2d8add1fe2781097e225/lib/src/builder.dart#L179) from:

```dart
child = new Column(
  crossAxisAlignment: CrossAxisAlignment.stretch,
  children: current.children,
);
```

to

```dart
child = new Column(
  crossAxisAlignment: CrossAxisAlignment.start,
  children: current.children,
);
```

and same [here](https://github.com/flutter/flutter_markdown/blob/265676fcaed7fab9b68e2d8add1fe2781097e225/lib/src/widget.dart#L183), will make it work like I want. Maybe we can add an option for that?

### LINKED ISSUE #72: pointy brackets("<" and ">") are not correctly shown in code blocks
wrong

### LINKED ISSUE #88: selected text copy
Hey, hello, thank you for your project. I met a problem in using it. If I want to copy text by long press, but it seems that there is no such function.

### LINKED ISSUE #94: MarkdownStyleSheet blockquote doesn't work.
Hello, I'm trying to change the font color in blockquote. 
```
MarkdownBody(
        data: data,
        styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
          blockquote: TextStyle(color: Colors.red),
        ),
      );
```

It doesn't change anything.

### LINKED ISSUE #95: Does not support dynamic text
Loading a markdown file on iOS will not render the text in the dynamic font size for each Theme class but instead the default non-sized version.

There is a large version here:

```
MarkdownBody(
  styleSheet:
    MarkdownStyleSheet.largeFromTheme(Theme.of(context)),
  data: _introText,
  onTapLink: (link) {
    FlutterWebBrowser.openWebPage(url: link);
  },
),
```

But this will not accommodate for body text size changes, either.

### LINKED ISSUE #98: Add support for creating MarkdownStyleSheet from CupertionTheme
When you use this plugin within an CupertinoApp and change the brightness to dark the text remains black. So you can't read it. I should be possible to use it without add a Theme widget around it and provide an extra ThemeData.

### LINKED ISSUE #101: Support flutter_web?
use on mobile flutter project ,work ok. but when I use on flutter_web, i got the following error:

image

### LINKED ISSUE #103: Compiler message: file:///Users/xxx/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.  - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///Users/xxx/flutter/packages/flutter/lib/src/painting/inline_span.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.         List<TextSpan> children = previous.text.children != null                                                 ^^^^^^^^
Compiler message:
file:///Users/calvinmuller/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///Users/calvinmuller/iStreet/Mobile/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.
        List<TextSpan> children = previous.text.children != null
                                                ^^^^^^^^

```
[✓] Flutter (Channel master, v1.7.2-pre.30, on Mac OS X 10.14.4 18E226, locale en-ZA)
    • Flutter version 1.7.2-pre.30 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision 14414f350a (8 hours ago), 2019-06-05 18:14:17 -0700
    • Engine revision 3371da1e09
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 9dcb026b26)
```

### LINKED ISSUE #108: flutter_markdown with Firestore image crash
I would like to display an image saved on firebase firestorage but if I do this the app crash:

![alt text](https://firebasestorage.googleapis.com/v0/b/appname-db7de.appspot.com/o/image1.PNG?alt=media&token=xxxxx

I'm doing something wrong?

### LINKED ISSUE #109: Center markdown vertically
Heyy,

Is there a possibility to Center the Markdown vertically in a Container if there is not enough text that you can scroll?

image

In this example the text should be positioned at the yellow box

Thanks in advance.

### LINKED ISSUE #118: Cannot extract a file path from a resource URI
As the title says. When I try to load an image using `resource:assets/image.jpg`, I get the following exception:

```
Exception Caught By widgets library

The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(411.4, 683.4), devicePixelRatio: 2.6, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false)):

Unsupported operation: Cannot extract a file path from a resource URI
```

I've got no idea why it happens. Hope there's a solution to this.

### LINKED ISSUE #120: Network image URIs should be HTML-unescaped
If an image tag has query parameters, the `markdown` library will correctly HTML-escape `&` to `&amp;`.

When `flutter_markdown` then takes that URI and passes it to `Image.network`, it should unescape those ampersands. 

Not all web browsers will resolve escaped ampersands in the URI.

For example, the following input will result in an HTTP 403 instead of loading the image:

```markdown
here is an image:

![Image](https://preview.redd.it/sg3q5cuedod31.jpg?width=640&crop=smart&auto=webp&s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f)
```

An image will be constructed using the raw HTML attribute `src`:

https://github.com/flutter/flutter_markdown/blob/0855cc0a6bc7fab3e60b76d1d9ea85bc1f00278d/lib/src/builder.dart#L235

Which will be (correctly) HTML escaped via

https://github.com/dart-lang/markdown/blob/bcda5112a1b001fe3cad8ac6c95ff6bc1f20cc56/lib/src/inline_parser.dart#L1030

The result is a call to `new Image.network` with the following uri:

```
https://preview.redd.it/sg3q5cuedod31.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f
```

Which results in an HTTP 403.

One possible fix is to call `Image.network` as follows:

```dart
child = new Image.network(uri.toString().replaceAll('&amp;', '&'), width: width, height: height);
```

### LINKED ISSUE #127: dart:io doesn't support flutter web
I can't use it on flutter web. beacuse the dart:io lib isn't support web platform.

### LINKED ISSUE #142: Cleanup the resolved issues

### LINKED ISSUE #147: How to set list bullet align to top (start)?
Hello, I want to set the bullet align to top like this:

image

I don't find any attribute to change the text align for the bullet list. It is possible?

### LINKED ISSUE #150: Counted lists are gonna centered (?!)
My counted lists are gonna centered vertically (the numbers). Why? I want it like real markdown on the first line! 😢 

Bildschirmfoto 2019-11-22 um 23 56 23

### LINKED ISSUE #151: Centeralize horizontally and vertically
Hey,

Is it possible to centeralize the MarkdownBody vertically and horizontally inside a Padding widget?
The description ("There are 4...") should be horizontally aligned with the title ("Cakes"). I have put the example code to this snippet after the image.
Screenshot_1574594012

```
Container(
      alignment: Alignment.center,
      //width: MediaQuery.of(context).size.width,
      height: 175,
      child: Stack(
        children: <Widget>[
          Container(
            width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
                image: DecorationImage(
                    image: AssetImage(this.backgroundPath), fit: BoxFit.cover)),
          ),
          Padding(
            padding: EdgeInsets.only(top: 140),
            child: Container(
              height: 50,
              child: Center(
                child: MarkdownBody(
                  data: 'There are **4 products** in this view.',
                ),
              ),
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(15),
                    topRight: Radius.circular(15),
                  ),
                  color: Colors.white),
            ),
          ),
          Center(
            child: Text(
              this.title,
              style: textTheme,
            ),
          )
        ],
      ),
    )
```

### PR DESCRIPTION
**Pull request by KagurazakaHanabi**
Closes #62, closes #151 
Closes #88 
Closes #94 
Closes #98 
Closes #101 
Closes #127 
Closes #147 
Closes #150 

#69 closes #95 
#102 fixes #103 
dart-lang/markdown#262 fixes #72 
dart-lang/markdown#275 fixes #58, fixes #108, fixes #120 
closes #48, closes #53, closes #109, closes #118, closes #142

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
Thank you so much for your work on this, @KagurazakaHanabi

**Comment by domesticmouse** [comment]
Is it fair to say this PR is blocked on https://github.com/dart-lang/markdown/pull/269 landing?

**Comment by KagurazakaHanabi** [comment]
No, but if that PR land, will fix a bug

File: lib/src/style_sheet.dart [hunk 1]
```diff
@@ -235,12 +313,50 @@ class MarkdownStyleSheet {
...
-      horizontalRuleDecoration:
-          horizontalRuleDecoration ?? this.horizontalRuleDecoration,
+      horizontalRuleDecoration: horizontalRuleDecoration ?? this.horizontalRuleDecoration,
       textScaleFactor: textScaleFactor ?? this.textScaleFactor,
     );
   }
 
+  /// Returns a new text style that is a combination of this style and the given
+  /// [other] style.
+  MarkdownStyleSheet merge(MarkdownStyleSheet other) {
```
Comment (domesticmouse) [inline lib/src/style_sheet.dart]: Can you add some tests for this functionality? Untested code will eventually break.

Comment (KagurazakaHanabi) [reply lib/src/style_sheet.dart]: Done

File: lib/src/builder.dart [hunk 2]
```diff
@@ -95,6 +94,7 @@ class MarkdownBuilder implements md.NodeVisitor {
   /// Creates an object that builds a [Widget] tree from parsed Markdown.
   MarkdownBuilder({
     @required this.delegate,
+    @required this.selectable,
```
Comment (domesticmouse) [inline lib/src/builder.dart]: I feel like marking this field as `@required` makes this (technically) a breaking change. Well it'll add squiggles to people's code on update. 

If this break makes sense, I'll bump the version numbers to be in alignment with semver, but I'm wondering if we can drop the `@required` and just default it appropriately. 

If I understand correctly, the previous default was to make all code not selectable, but is that the best default? I'm leaning towards defaulting `selectable` to true and dropping the `@required`.

Thoughts?

File: lib/src/widget.dart [hunk 3]
```diff
@@ -125,8 +132,8 @@ class _MarkdownWidgetState extends State<MarkdownWidget>
   }
 
   void _parseMarkdown() {
-    final MarkdownStyleSheet styleSheet =
-        widget.styleSheet ?? MarkdownStyleSheet.fromTheme(Theme.of(context));
+    // TODO: Auto detect app is using Cupertino or Material
```
Comment (domesticmouse) [inline lib/src/widget.dart]: Per a https://github.com/flutter/flutter_markdown/pull/99#discussion_r348788617 I'd prefer to expose Cupertino vs Material to the user of the Widget, defaulting to Material, because using Material on iOS makes sense in various places, e.g. the web, and there are places where using Cupertino makes sense where it isn't iOS, e.g. macOS.

File: lib/src/builder.dart (hunk 2 above)
Comment (KagurazakaHanabi) [reply lib/src/builder.dart]: `@required` help me avoid a mistake like #139

`MarkdownBuilder` only used in `_MarkdownWidgetState`, maybe is not a breaking change?

I agree with you, maybe defaults to true is better

File: lib/src/widget.dart (hunk 3 above)
Comment (KagurazakaHanabi) [reply lib/src/widget.dart]: How about add a property like `bool isMaterialTheme` to `MarkdownStyleSheet` and defaults to false?

If using Material, `CupertinoTheme.of(context)` will return `MaterialBasedCupertinoThemeData`

https://github.com/flutter/flutter/blob/6eb0a0e3715c6eeb7a2733f74cf6e741fe796ef6/packages/flutter/lib/src/material/theme.dart#L149

Comment (domesticmouse) [reply lib/src/widget.dart]: I'd put the default as assuming people are using the material widget set. That way the property would be something along the lines of `isCupertino`, defaulting to false.

Thoughts?

Comment (KagurazakaHanabi) [reply lib/src/widget.dart]: It’s my idea https://github.com/flutter/flutter_markdown/commit/7ce0811db5b70b9f0ee1e29a395f11f43edd2ba9

**Comment by domesticmouse** [comment]
Please resolve conflicts, thanks!

**Comment by KagurazakaHanabi** [comment]
Tell me how to fix the CI error about dart:html please

**Comment by domesticmouse** [comment]
> Tell me how to fix the CI error about dart:html please

Hey @RedBrogdon, any ideas on who we should chat with about making conditional flutter web code work in tests?

**Comment by KagurazakaHanabi** [comment]
I created an issue #45521 and I fixed the test errors
