### PR TITLE
Fix baseline in lists

### LINKED ISSUE #169: Baseline looks broken when using multi-byte characters
When the markdown was described using Japanese and displayed on the screen, the baseline appeared shifted.

Is there any way to deal with it?
Attach source code and screen capture.

```dart

const String _markdownData = """

## This is OK.
1. hoge
* fuga

## This looks different in the baseline
2. ほげ
* ふが


""";

class SampleMarkdownPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('issue markdown'),
        centerTitle: true,
      ),
      body: Container(
        child: Markdown(
          selectable: true,
          data: _markdownData,
          styleSheet: markdownTheme,
        ),
      ),
    );
  }
}
```

Screenshot_20200106-171657

# flutter doctor -v
[√] Flutter (Channel unknown, v1.13.2, on Microsoft Windows [Version 10.0.18362.535], locale ja-JP)
    • Flutter version 1.13.2 at C:\tools\flutter
    • Framework revision 4944622b5d (4 weeks ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\sh-ogawa\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593

[!] VS Code, 32-bit edition (version 1.38.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Pixel 3a • 96PAY0YLSB • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

### PR DESCRIPTION
**Pull request by KagurazakaHanabi**
Closes #169

### CODE REVIEW

**Comment by sh-ogawa** [comment]
@domesticmouse 
Is there any reason that this pull request will not be merged?

**Comment by domesticmouse** [comment]
@sh-ogawa and @KagurazakaHanabi apologies for missing this PR earlier. This change looks good to me, landing now.

File: lib/src/builder.dart [hunk 1]
```diff
@@ -257,8 +257,10 @@ class MarkdownBuilder implements md.NodeVisitor {
           } else {
             bullet = _buildBullet(_listIndents.last);
           }
+          // See #147 and #169
           child = Row(
-            crossAxisAlignment: CrossAxisAlignment.start, // See #147
+            textBaseline: TextBaseline.alphabetic,
+            crossAxisAlignment: CrossAxisAlignment.baseline,
```
Comment (creativecreatorormaybenot) [inline lib/src/builder.dart:263]: Hi @KagurazakaHanabi - this change makes Markdown lists incompatible with intrinsic sizing.

See https://github.com/flutter/flutter/issues/71990#issuecomment-747149574.

Do you have an idea how we can remove the `baseline` alignment?
